# Generated by Django 3.2.5 on 2021-08-19 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_info', '0002_information_on_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='on_display',
            field=models.BooleanField(),
        ),
    ]
