# Generated by Django 3.2.5 on 2021-07-15 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=255)),
                ('button_text', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='media/slides/%Y/%m')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
