# Generated by Django 3.2.5 on 2021-07-16 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0004_alter_slider_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('fb_link', models.URLField(max_length=255)),
                ('ista_link', models.URLField(max_length=255)),
                ('photo', models.ImageField(upload_to='media/team/%Y/%m/%d/')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
