# Generated by Django 3.2.5 on 2021-07-17 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0005_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='ista_link',
            new_name='insta_link',
        ),
    ]
