# Generated by Django 3.2.5 on 2021-07-17 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0006_rename_ista_link_team_insta_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='youtube_link',
            field=models.URLField(default=' ', max_length=255),
        ),
    ]
