# Generated by Django 3.2.5 on 2021-08-19 15:21

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0008_alter_team_youtube_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_contect', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
