# Generated by Django 3.2.5 on 2021-07-17 07:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Youtuber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('photo', models.ImageField(upload_to='media/ytubers/%Y/%m')),
                ('video_url', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('height', models.DecimalField(decimal_places=2, max_digits=3)),
                ('crew', models.CharField(max_length=100)),
                ('camera_type', models.CharField(max_length=100)),
                ('subs_countnt', models.CharField(max_length=100)),
                ('catogery', models.CharField(max_length=100)),
                ('is_featured', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
