# Generated by Django 3.2.5 on 2021-07-17 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtuber',
            name='camera_type',
            field=models.CharField(choices=[('canon', 'canon'), ('nikon', 'nikon'), ('sony', 'sony'), ('red', 'red'), ('fuji', 'fuji'), ('panasonic', 'panasonic'), ('others', 'others')], max_length=100),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='catogery',
            field=models.CharField(choices=[('code', 'code'), ('tech_review', 'tech_review'), ('vlogs', 'vlogs'), ('comedy', 'comedy'), ('education', 'education'), ('science', 'science'), ('others', 'others')], max_length=100),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='crew',
            field=models.CharField(choices=[('solo', 'solo'), ('small', 'small'), ('large', 'large')], max_length=100),
        ),
    ]
