# Generated by Django 3.2.5 on 2021-07-17 07:48

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0002_auto_20210717_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtuber',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
