# Generated by Django 3.2.5 on 2021-08-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_alter_hiretuber_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiretuber',
            name='phone_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
